# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 368023621bc4beb4c23a63670ff05d97e1b9b8370fa04d6235b298661f56e4c514b406e651cd26523868b94f7f9c0ee793827d71fb3f57b1bcafed25843a8448

test:
  secret_key_base: ef7e075533233450e14bf2d569d5896a7c08c3d4d1fdb9c72ee2d1f61899e5a7fa3aa68059b4d0e315cb5bd8963bd417c5ac8eb9a698d89c70dc4eded36fbe06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
